---
# (avk) First, gathering facts of all nodes is necessary to have access to variables of others nodes (such as hostvars[groups['control-bus'][0])
- name: Gathering facts of all nodes
  hosts: all
  tasks:
  - setup:

- name: Deploy Ombt-server
  hosts: ombt-server
  roles:
    - ombt

- name: Deploy Ombt-client
  hosts: ombt-client
  roles:
    - ombt

- name: Deploy Ombt-control
  hosts: ombt-control
  roles:
    - ombt

